import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MENUITEMS.MAIN.TEXT',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  {
      path: '',
      title: 'Purchese order list',
      iconType: 'feather',
      icon: 'list',
      class: 'menu-toggle',
      groupTitle: false,
      badge: '',
      badgeClass: '',
      role: ['Logistic'],
      submenu: []
  },

  

  {
  
    path: '/admin/dashboard/dashboard2',
    title: 'Raw Materials',
    iconType: '',
    icon: 'grid',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Lab'],
    submenu: [

      {
        path: '',
        title: 'Buxaite',
        iconType: 'feather',
        icon: 'feather',
        class: 'ml-sub-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [
          {
            path: '/lab',
            title: 'Bag creation',
            iconType: '',
            icon: 'grid',
            class: 'ml-sub-menu',
            groupTitle: false,
            badge: '',
            badgeClass: '',
            role: [''],
            submenu: [
             {
                path: '/lab/bag-creation-list',
                title: ' Sample Collection List',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/rmr-lab',
                title: 'Sample recieved at Lab',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/final-result',
                title: 'Sampling Result ',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
          
        ],
      },
      {
        path: '/lab/buxaite',
        title: 'Job assignment',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/lab/final-result',
        title: 'Final result',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
    },
    {
      path: '/lab',
      title: 'Quality Clearance',
      iconType: '',
      icon: 'grid',
      class: 'ml-menu3',
      groupTitle: false,
      badge: '',
      badgeClass: '',
      role: [''],
      submenu: [],
    },
    
      
        ],
      },
      {
        path: '/lab/amd-domestic-buxaite',
        title: 'Heavy furnace oil(HFO)',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu',
        groupTitle: true,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [
          {
            path: '/lab',
            title: 'Bag creation',
            iconType: '',
            icon: 'grid',
            class: 'ml-sub-menu',
            groupTitle: false,
            badge: '',
            badgeClass: '',
            role: [''],
            submenu: [
             {
                path: '/lab/bag-creation-list',
                title: ' Sample Collection Form',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/rmr-lab',
                title: 'Sample recieved at Lab',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/final-result',
                title: 'Sampling Result ',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
          
        ],
      },
      {
        path: '/lab',
        title: 'Job assignment',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/lab',
        title: 'Final result',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
    },
    {
      path: '/lab',
      title: 'Quality Clearance',
      iconType: '',
      icon: 'grid',
      class: 'ml-menu3',
      groupTitle: false,
      badge: '',
      badgeClass: '',
      role: [''],
      submenu: [],
    },
      
      
        ],
      },

      {
        path: '/lab/amd-domestic-buxaite',
        title: 'CLO (Fuel Oil)',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu',
        groupTitle: true,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [
          {
            path: '/lab',
            title: 'Bag creation',
            iconType: '',
            icon: 'grid',
            class: 'ml-sub-menu',
            groupTitle: false,
            badge: '',
            badgeClass: '',
            role: [''],
            submenu: [
             {
                path: '/lab/bag-creation-list',
                title: ' Sample Collection Form',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/rmr-lab',
                title: 'Sample recieved at Lab',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/final-result',
                title: 'Sampling Result ',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
          
        ],
      },
      {
        path: '/lab',
        title: 'Job assignment',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/lab',
        title: 'Final result',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
    },
    {
      path: '/lab',
      title: 'Quality Clearance',
      iconType: '',
      icon: 'grid',
      class: 'ml-menu3',
      groupTitle: false,
      badge: '',
      badgeClass: '',
      role: [''],
      submenu: [],
    },
      
      
        ],
      },

      {
        path: '/lab/amd-domestic-buxaite',
        title: 'Light Diesel Oil',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu',
        groupTitle: true,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [
          {
            path: '/lab',
            title: 'Bag creation',
            iconType: '',
            icon: 'grid',
            class: 'ml-sub-menu',
            groupTitle: false,
            badge: '',
            badgeClass: '',
            role: [''],
            submenu: [
             {
                path: '/lab/bag-creation-list',
                title: ' Sample Collection Form',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/rmr-lab',
                title: 'Sample recieved at Lab',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/final-result',
                title: 'Sampling Result ',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
          
        ],
      },
      {
        path: '/lab',
        title: 'Job assignment',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/lab',
        title: 'Final result',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
    },
    {
      path: '/lab',
      title: 'Quality Clearance',
      iconType: '',
      icon: 'grid',
      class: 'ml-menu3',
      groupTitle: false,
      badge: '',
      badgeClass: '',
      role: [''],
      submenu: [],
    },
      
      
        ],
      },

      {
        path: '/lab/amd-domestic-buxaite',
        title: 'High Speed Diesel',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu',
        groupTitle: true,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [
          {
            path: '/lab',
            title: 'Bag creation',
            iconType: '',
            icon: 'grid',
            class: 'ml-sub-menu',
            groupTitle: false,
            badge: '',
            badgeClass: '',
            role: [''],
            submenu: [
             {
                path: '/lab/bag-creation-list',
                title: ' Sample Collection Form',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/rmr-lab',
                title: 'Sample recieved at Lab',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/final-result',
                title: 'Sampling Result ',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
          
        ],
      },
      {
        path: '/lab',
        title: 'Job assignment',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/lab',
        title: 'Final result',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
    },
    {
      path: '/lab',
      title: 'Quality Clearance',
      iconType: '',
      icon: 'grid',
      class: 'ml-menu3',
      groupTitle: false,
      badge: '',
      badgeClass: '',
      role: [''],
      submenu: [],
    },
      
      
        ],
      },

      {
        path: '/lab/amd-domestic-buxaite',
        title: 'Lime',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu',
        groupTitle: true,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [
          {
            path: '/lab',
            title: 'Bag creation',
            iconType: '',
            icon: 'grid',
            class: 'ml-sub-menu',
            groupTitle: false,
            badge: '',
            badgeClass: '',
            role: [''],
            submenu: [
             {
                path: '/lab/bag-creation-list',
                title: ' Sample Collection Form',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/rmr-lab',
                title: 'Sample recieved at Lab',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/final-result',
                title: 'Sampling Result ',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
          
        ],
      },
      {
        path: '/lab',
        title: 'Job assignment',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/lab',
        title: 'Final result',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
    },
    {
      path: '/lab',
      title: 'Quality Clearance',
      iconType: '',
      icon: 'grid',
      class: 'ml-menu3',
      groupTitle: false,
      badge: '',
      badgeClass: '',
      role: [''],
      submenu: [],
    },
      
      
        ],
      },

      {
        path: '/lab/amd-domestic-buxaite',
        title: 'Caustic Soda Lye',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu',
        groupTitle: true,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [
          {
            path: '/lab',
            title: 'Bag creation',
            iconType: '',
            icon: 'grid',
            class: 'ml-sub-menu',
            groupTitle: false,
            badge: '',
            badgeClass: '',
            role: [''],
            submenu: [
             {
                path: '/lab/bag-creation-list',
                title: ' Sample Collection Form',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/rmr-lab',
                title: 'Sample recieved at Lab',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/final-result',
                title: 'Sampling Result ',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
          
        ],
      },
      {
        path: '/lab',
        title: 'Job assignment',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/lab',
        title: 'Final result',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
    },
    {
      path: '/lab',
      title: 'Quality Clearance',
      iconType: '',
      icon: 'grid',
      class: 'ml-menu3',
      groupTitle: false,
      badge: '',
      badgeClass: '',
      role: [''],
      submenu: [],
    },
      
      
        ],
      },

      {
        path: '/lab/amd-domestic-buxaite',
        title: 'Coal',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu',
        groupTitle: true,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [
          {
            path: '/lab',
            title: 'Bag creation',
            iconType: '',
            icon: 'grid',
            class: 'ml-sub-menu',
            groupTitle: false,
            badge: '',
            badgeClass: '',
            role: [''],
            submenu: [
             {
                path: '/lab/bag-creation-list',
                title: ' Sample Collection Form',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/rmr-lab',
                title: 'Sample recieved at Lab',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
              {
                path: '/lab/final-result',
                title: 'Sampling Result ',
                iconType: '',
                icon: '',
                class: 'ml-menu3',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
              },
          
        ],
      },
      {
        path: '/lab',
        title: 'Job assignment',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/lab',
        title: 'Final result',
        iconType: '',
        icon: 'grid',
        class: 'ml-menu3',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
    },
    {
      path: '/lab',
      title: 'Quality Clearance',
      iconType: '',
      icon: 'grid',
      class: 'ml-menu3',
      groupTitle: false,
      badge: '',
      badgeClass: '',
      role: [''],
      submenu: [],
    },
      
      
        ],
      },
     
    ],
    },

  
];